back-end/.eslintrc.json
back-end/src/app/application/TestService.ts
back-end/src/main.ts
back-end/tsconfig.json

chore: Updated ESLint to be more strict

---

back-end/.eslintrc.json
back-end/jest.config.ts
back-end/src/tests/integration_tests/A.ts
back-end/src/tests/integration_tests/B.ts
back-end/src/tests/integration_tests/sample.integration.test.ts

Examples of mocking and spying (from docs by the way).

chore: added test examples

---

.github/workflows/ci.yml
.github/workflows/release.yml
release.config.js

Reverts UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#74

Revert "Configuring CICD"

---

back-end/src/app/adapter/DependencyInjections.ts
back-end/src/app/application/TestService.ts
back-end/src/main.ts

A single file to control dependency injections.
The file is called "DependencyInjections.ts". It contains all the tokens as well as injections so we can easily swap out different implementations when needed.

I88 Dependency Injection File

---

back-end/src/main.ts
back-end/src/resources/log4js-config.json

small changes, focused on mainly changing the log4js-config.json

fix: updated logging with log4js to resolve other depedency issues

---

front-end/ReactFE/package-lock.json

reset old package-lock.json to previous

fix: update package-lock.json

---

back-end/.eslintrc.json
back-end/package-lock.json
back-end/package.json
back-end/src/app/adapter/Controllers/Handlers/UserDeleteHandler.ts
back-end/src/app/adapter/Controllers/UserController.ts
back-end/src/app/adapter/DependencyInjections.ts
back-end/src/app/adapter/SQLRepositories/User/UserSQLRepository.ts
back-end/src/app/application/UserService.ts
back-end/src/app/application/util.ts
back-end/src/app/domain/User.ts
back-end/src/app/domain/interfaces/repositories/IUserRepository.ts
back-end/src/main.ts
back-end/src/resources/config.ts
back-end/src/tests/unit_tests/UserDeleteHandler.unit.test.ts
back-end/src/tests/unit_tests/common_test_code/util_test.ts
back-end/src/tests/unit_tests/mocked_repository/MockUserRepository.ts
back-end/src/tests/unit_tests/util.unit.test.ts

- Added `authenticate` method for protected routes.
- Fixed issues with User domain objects and User SQL/Service methods
- Minor changes to eslint
- Added User Delete API

I97 User Delete

---

back-end/src/app/application/util.ts
back-end/src/resources/database/migrations/20240306052851-V1.0.4-caseSensitiveUserId.js
back-end/src/resources/database/migrations/sqls/20240306052851-V1.0.4-caseSensitiveUserId-down.sql
back-end/src/resources/database/migrations/sqls/20240306052851-V1.0.4-caseSensitiveUserId-up.sql
back-end/src/tests/unit_tests/util.unit.test.ts

Function to generate a random alphanumeric string given a specified length.
We will be using this for generating userId.
Probability of guessing the correct userId is $`\frac{1}{62^n}`$ where n is the specified length.

I18 generate random alphanumeric string

---

back-end/src/app/adapter/Controllers/Handlers/UserDeleteHandler.ts
back-end/src/app/adapter/DependencyInjections.ts
back-end/src/app/adapter/Loggers/Log4jsLogger.ts
back-end/src/app/domain/factory/LoggerFactory.ts
back-end/src/app/domain/interfaces/ILogger.ts
back-end/src/tests/unit_tests/UserDeleteHandler.unit.test.ts

Logger factory to create generic loggers for each class

I85 Logger factory

---

back-end/src/app/domain/RequestStatusEnum.ts
back-end/src/app/domain/RequestTypeEnum.ts
back-end/src/app/domain/UserRequest.ts
back-end/src/app/domain/interfaces/repositories/IUserRequestRepository.ts
back-end/src/resources/database/migrations/20240313001306-V1.0.5-requestTable.js
back-end/src/resources/database/migrations/sqls/20240313001306-V1.0.5-requestTable-down.sql
back-end/src/resources/database/migrations/sqls/20240313001306-V1.0.5-requestTable-up.sql

Added migration script to create a new SQL table called `Request` to store sign up and password reset requests from users.
Correspondingly created domain objects UserRequest, and the enums RequestStatusEnum and RequestTypeEnum as well as the interface to interact with the Request table: IUserRequestRepository.
UML Diagram will be in the google drive.

I123 SQL Table and domain object/interfaces for signup/passwordRest Request 

---

back-end/src/app/domain/Survey.ts
back-end/src/app/domain/SurveyAnswer.ts
back-end/src/app/domain/SurveyQuestion.ts
back-end/src/app/domain/interfaces/repositories/ISurveyAnswerRepository.ts
back-end/src/app/domain/interfaces/repositories/ISurveyQuestionRepository.ts
back-end/src/app/domain/interfaces/repositories/ISurveyRepository.ts

Setting up interfaces and domain objects for Survey-related logic. This involves creating the Survey, SurveyAnswer, and SurveyQuestion domain objects as well as their corresponding repository interfaces: ISurveyRepository, ISurveyAnswerRepository, ISurveyQuestionRepository.
UML Diagrams will be documented in the Google drive.
The code has enough clarity to be self-documenting, but some methods require further documentation, which will also be documented in the Google drive.

I117 Set up interfaces and domain objects for Survey

---

back-end/src/app/adapter/Controllers/Handlers/SignUpHandler.ts
back-end/src/app/adapter/SQLRepositories/User/UserSQLRepository.ts
back-end/src/app/domain/User.ts
back-end/src/app/domain/UserRequest.ts
front-end/ReactFE/app/context/AuthContext.tsx
front-end/ReactFE/app/service/apiService.tsx

Addressed the lint checks that are failing during CI. Also commented out the agreeToEthics field in the Users.ts file for now. Will be added in next ID.

Addressed build check failure and Users.ts file changes

---

back-end/src/app/adapter/Controllers/Handlers/CreateQuestionHandler.ts
back-end/src/app/adapter/Controllers/Handlers/CreateUserHandler.ts
back-end/src/app/adapter/Controllers/Handlers/LoginAuthHandler.ts
back-end/src/app/adapter/Controllers/Handlers/QuestionGetAllHandler.ts
back-end/src/app/adapter/Controllers/Handlers/SignUpHandler.ts
back-end/src/app/adapter/Controllers/Handlers/SurveyAddHandler.ts
back-end/src/app/adapter/Controllers/Handlers/SurveyGetUsersSubmittedHandler.ts
back-end/src/app/adapter/Controllers/Handlers/UserDeleteHandler.ts
back-end/src/app/adapter/DependencyInjections.ts
back-end/src/app/application/SurveyQuestionService.ts
back-end/src/app/application/SurveyService.ts
back-end/src/main.ts

- Update old dependency injections in code
- Refactored DependencyInjection tokens to follow current convention

Update old Dependency Injections

---

back-end/src/app/adapter/Controllers/QuestionContoller.ts

- Refactored QuestioController to follow controller conventions and removed some redundant injections

Issue 183 Refactor

---

back-end/src/app/adapter/Controllers/Handlers/AnswersUpdateHandler.ts
back-end/src/app/adapter/Controllers/Handlers/CreateQuestionHandler.ts
back-end/src/app/adapter/Controllers/Handlers/SurveyGetHandler.ts
back-end/src/app/adapter/Controllers/SurveyController.ts
back-end/src/app/adapter/SQLRepositories/Survey/AnswerSQLRepository.ts
back-end/src/app/adapter/SQLRepositories/Survey/QuestionSQLRepository.ts
back-end/src/app/application/SurveyQuestionService.ts
back-end/src/app/application/SurveyService.ts
back-end/src/app/domain/QuestionTypeEnum.ts
back-end/src/app/domain/SurveyQuestion.ts
back-end/src/app/domain/interfaces/repositories/ISurveyAnswerRepository.ts
back-end/src/app/domain/interfaces/repositories/ISurveyQuestionRepository.ts
back-end/src/tests/unit_tests/SurveyGetAllHandler.test.ts
back-end/src/tests/unit_tests/SurveyGetHandler.unit.test.ts
back-end/tsconfig.json

- Load questions and answers of a survey for a user
- Returns an array of SurveyQuestion objects.

I177 load survey content for a user

---

back-end/src/app/adapter/SQLRepositories/SQLConfiguration.ts
back-end/src/app/adapter/SQLRepositories/Survey/AnswerSQLRepository.ts
back-end/src/tests/mocked_repository/MockAnswerRepository.ts
docker-compose.test.yml

- Fix MockAnswerRepo not implementing all required interface methods
- Fix AnswerSQLRepo update bug; missed edge case
- Added better logging for repo
- Updated CI pipeline

fix: hotfix bugs related to answer repos and added logging

---

back-end/src/app/adapter/Controllers/Handlers/CreateAnswerHandler.ts
back-end/src/tests/unit_tests/CreateAnswerHandler.test.ts
back-end/src/tests/unit_tests/SurveyGetAllResponseHandler.test.ts

Fixed the validation issue with createAnswerHandler and updated its tests.
Commented out the test case that was creating that response excel file and failing to remove it.

fix: minor validation error fix in createAnswerHandler and tests

---

back-end/src/resources/database/migrations/20240403165230-add-another-test-user.js
back-end/src/resources/database/migrations/sqls/20240403165230-add-another-test-user-down.sql
back-end/src/resources/database/migrations/sqls/20240403165230-add-another-test-user-up.sql

UserId: `testuser`
Pass: `smkfomg453AM$`

added a non-admin user to the db

---

back-end/src/tests/integration_tests/api_tests/apiCreateUser.test.ts
back-end/src/tests/integration_tests/api_tests/apiGetSurvey.test.ts
back-end/src/tests/integration_tests/api_tests/apiGetUserSubmitted.test.ts
back-end/src/tests/integration_tests/api_tests/apiLoginAuth.test.ts
back-end/src/tests/integration_tests/api_tests/testSqlCommands.ts

Adding test script to test api… "…/survey/:surveyId/user" with parameters and testSqlCommands.ts for SQL test queries. Contents pulled from PR #190.

Test(From Test-172 branch and PR#190): 

---

back-end/src/app/adapter/SQLRepositories/User/UserSQLRepository.ts

- Fix SQL queries in code to have correct matching capitalization for table names.

fix: fix incorrect capitalization of db table names in queries

---

back-end/src/app/adapter/Controllers/Handlers/RequestGetAllHandler.ts
back-end/src/app/adapter/Controllers/UserController.ts
back-end/src/app/adapter/DTOs/RequestDTO.ts
back-end/src/app/adapter/SQLRepositories/SQLConfiguration.ts
back-end/src/app/adapter/SQLRepositories/UserRequest/UserRequestSQLRepository.ts
back-end/src/app/application/UserRequestService.ts
back-end/src/app/domain/RequestStatusEnum.ts
back-end/src/app/domain/RequestTypeEnum.ts

- GET /user/request API was accidentally deleted by one of the previous merge commits.
- This will add the API back

I194 - Readding this API because it was accidentally deleted

---

front-end/ReactFE/app/Screen/SurveyList.jsx
front-end/ReactFE/e2e/helperFunctions.e2e.test.ts
front-end/ReactFE/e2e/issue155.e2e.test.ts
front-end/ReactFE/e2e/login.e2e.test.ts
front-end/ReactFE/e2eHelpers/e2eHelpers.js
front-end/ReactFE/package-lock.json
front-end/ReactFE/package.json
front-end/ReactFE/yarn.lock

+ added react native date picker to fix apk build fail

test hooks and E2E testing
